<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__mr-2</name>
   <tag></tag>
   <elementGuidId>9684904c-cac6-4868-b966-50b7e7f70973</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maid-modal___BV_modal_body_']/div[2]/div[2]/div[2]/div/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mr-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/one-time-icon.a38b266d.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maid-modal___BV_modal_body_&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;maid-modal-detail col-md-6 col-xl-6&quot;]/div[@class=&quot;form-row d-none d-sm-flex&quot;]/div[@class=&quot;col-lg-6 col-12&quot;]/button[@class=&quot;btn choose-maid-btn my-1 btn-success btn-block&quot;]/img[@class=&quot;mr-2&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maid-modal___BV_modal_body_']/div[2]/div[2]/div[2]/div/button/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/button/img</value>
   </webElementXpaths>
</WebElementEntity>
