<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left._rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>589fc27f-5fe9-403e-8d94-be1e19771856</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq27mwYVsJUvddV-_6kj8POhq8YHZjNtTBwmtOxi1rqdrvW2fSHQ6iNmFSZI1lG0E3eTlxqS9W5huFbibgzD2Q6SAwT-J92vydHPNq0Z2GPqlySgOAaSzPBogDbOXACuFjDZbJa0RRD0OskUB46Xn89xxWj9rHlet4BVGyeVG-Lh4iwrzMMZc5UNNsFI0EWD_r9ZXWTTOet8L2OvMIfMUDB_wxMaIneb4oywj6c54Y4gtEwuMk68&amp;k=6LcMZR0UAAAAALgPMcgHwga7gY5p8QMg1Hj-bmUv</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/P_USE/26/Page_Bluuu/iframe__c-wzxiw7n6xqy2</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq27mwYVsJUvddV-_6kj8POhq8YHZjNtTBwmtOxi1rqdrvW2fSHQ6iNmFSZI1lG0E3eTlxqS9W5huFbibgzD2Q6SAwT-J92vydHPNq0Z2GPqlySgOAaSzPBogDbOXACuFjDZbJa0RRD0OskUB46Xn89xxWj9rHlet4BVGyeVG-Lh4iwrzMMZc5UNNsFI0EWD_r9ZXWTTOet8L2OvMIfMUDB_wxMaIneb4oywj6c54Y4gtEwuMk68&amp;k=6LcMZR0UAAAAALgPMcgHwga7gY5p8QMg1Hj-bmUv')])[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
