<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_</name>
   <tag></tag>
   <elementGuidId>388f0b20-c2e0-413a-bf91-56196b23374c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.my-2.text-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='warning-maid-available-modal___BV_modal_body_']/div[2]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-2 text-center</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>เนื่องจากมีผู้ใช้บริการเป็นจำนวนมาก ทำให้แม่บ้านของเรา ไม่สามารถให้บริการได้ในเวลาดังกล่าว โปรดเลือกใช้บริการแม่บ้านของเราในช่วงเวลาอื่น และอภัยในความไม่สะดวก เราจะทำงานอย่างเต็มที่ เพื่อจัดหาแม่บ้านเพื่อคุณ ขอบคุณสำหรับการใช้บริการ</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;warning-maid-available-modal___BV_modal_body_&quot;)/div[@class=&quot;mx-2 mb-2&quot;]/div[1]/p[@class=&quot;my-2 text-center&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='warning-maid-available-modal___BV_modal_body_']/div[2]/div/p</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@bluuu'])[2]/following::p[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info@bluuu.co'])[2]/following::p[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ปิด'])[1]/preceding::p[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='เนื่องจากมีผู้ใช้บริการเป็นจำนวนมาก ทำให้แม่บ้านของเรา ไม่สามารถให้บริการได้ในเวลาดังกล่าว']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/p</value>
   </webElementXpaths>
</WebElementEntity>
